### ISSUE TITLE
Have you tried using pointnet as a feature extractor for training? 

### ISSUE THREAD

**Issue by HHHTTY** [auniquesun/CrossPoint-DDP#1]
Have you tried using pointnet as a feature extractor for training? 
I have tried and failed, thank you! 
My guess is that pointnet uses a different set of parameters, etc. Thank you very much!

**Comment by auniquesun** [comment]
Hi, @HHHTTY , I haven't tried pointnet as the feature extractor. I used the default dgcnn point cloud encoder. Maybe you can refer to the official parameter settings of pointnet, such as the following projects [pointnet](https://github.com/charlesq34/pointnet), [pointnet.pytorch](https://github.com/fxia22/pointnet.pytorch), [pointnet2](https://github.com/yanx27/Pointnet_Pointnet2_pytorch)
