### ISSUE TITLE
failed while executing pt-cls.sh with pueue

### ISSUE THREAD

**Issue by megadl** [auniquesun/CrossPoint-DDP#2]
![image](https://github.com/auniquesun/CrossPoint-DDP/assets/43907558/957670f5-1bd8-4554-a41b-5325f0c3318a)
Could you please help me with this issue?

**Comment by auniquesun** [comment]
@megadl Have you addressed the problem? 

You can use the command, `pueue follow <id>` to check the running script and it will show you the Tracestack of the errors in the code.

For example, `pueue follow 1` to check the Tracestack of your first script. Hope it helpful!
